In [6]:
#建立list 矩陣運算
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8, 10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])
result1 = []
for i in range(5):
    result1.append(a[i] * b[i])
result3 = []
for i in range(5):
    result3.append(a[i] * 2)

result
result1
result3

[2, 6, 10, 14, 18]

In [9]:
import numpy
#透過list建立ndArray

a_array = numpy.array([1, 3, 5, 7, 9])
a_array * 2

b_array = numpy.array([2, 4, 6, 8, 10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [10]:
import numpy as np
#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8, 10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [11]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[95, 83, 93, 74, 93]

In [12]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100, size=5)

array([76, 57, 50, 75, 79])

In [13]:
import numpy as np
np.random.randint(50,high=100, size=(50,5))

array([[85, 92, 92, 53, 92],
       [84, 60, 68, 89, 86],
       [83, 62, 94, 65, 70],
       [85, 69, 75, 91, 71],
       [72, 83, 75, 83, 86],
       [88, 90, 88, 82, 75],
       [82, 97, 87, 89, 99],
       [96, 81, 70, 94, 68],
       [55, 50, 97, 52, 70],
       [90, 89, 60, 55, 83],
       [85, 81, 92, 86, 60],
       [96, 74, 65, 51, 73],
       [55, 70, 64, 72, 60],
       [89, 88, 59, 73, 74],
       [72, 84, 68, 84, 64],
       [53, 75, 86, 73, 50],
       [64, 58, 76, 96, 71],
       [64, 94, 56, 75, 54],
       [87, 79, 70, 50, 90],
       [58, 67, 52, 60, 96],
       [56, 67, 84, 73, 74],
       [57, 95, 94, 63, 71],
       [95, 90, 72, 50, 56],
       [85, 53, 87, 59, 51],
       [62, 82, 78, 99, 54],
       [71, 59, 95, 57, 82],
       [53, 98, 74, 76, 88],
       [83, 62, 65, 84, 80],
       [87, 90, 66, 95, 52],
       [71, 87, 81, 66, 82],
       [76, 97, 72, 70, 60],
       [85, 68, 70, 80, 50],
       [95, 79, 80, 75, 99],
       [71, 69, 84, 82, 56],
       [98, 95